### ISSUE TITLE
Welcome to Print-To-3D Discussions!

### ISSUE THREAD

**Issue by ghost** [p3d-dev/Print-To-3D#13] opened 2023-03-01 14:03 UTC
### Discussed in https://github.com/p3d-dev/Print-To-3D/discussions/2

<div type='discussions-op-text'>

<sup>Originally posted by **p3d-dev** August  3, 2022</sup>

## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

</div>

**Comment by ghost** [comment] 2023-03-01 14:07
![391E9990-E634-487A-BE3C-6D9199180C93](https://user-images.githubusercontent.com/79003022/222163586-0d65db5a-b3d3-4a3a-a5fd-7e37c9829dc8.jpeg)

Any idea why I get this on any print I try to slice

**Comment by p3d-dev** [comment] 2023-03-01 21:44
No idea. Unfortunately the print object "earbud pot" cannot be seen. Can you share the STL or a link to that STL, so we can try on our side ?

In case you have modified printer and/or process configuration, you can start fresh by long press the "+" icons in the sidebar and select in the pop up menu the item "Default". This will create new printer or process configuration respectively. Alternatively you can delete the only configuration and a new default will be generated. Next please press "+" in the top, search on your iPad for the folder "Print To 3D". There you should find the default files. Perhaps you start with "All_In_One.stl" and select that. The 3D view should return with that print object on top. If using these steps, the slicer does not work, then it gets mysterious.

Two additional questions: 
- which device and iOS version do you use ?
- the sidebar button design is a bit of a surprise. On our devices/simulator it looks different. Have you changed any Apple iOS setting, which can enable this mode ? Seeing this, perhaps a section separator line would look better.

**Comment by ghost** [comment] 2023-03-03 09:13
Hi All

Last questions first. 
Using iPad with an Apple processor running IpadOS 16.3.1, I have not made any settings changes I am aware of. Unless something like installing Grammarly can influence things. 

I think I may have isolated it to an issue with the Prusa MK3S+ template. The reasoning for this is that, after deleting the app completely and reinstalling on both iPhone and iPad it still would not slice. I tried adding new printer as suggested still without success. 

However the eureka moment came on using a different template and with this both iPhone and Ipad sliced successfully on the Ender 3 template file. Tried a few files and all were sliced successfully bar one that sliced but not well.

Hope info below helps,Prusa code template downloaded from templates
I am not ofay of this stuff but Should.  M83                ; set relative positioning for extruder.   Be M84

The file below would not slice properly. (unable to add as an stl file had to zip it)
[9 Draw Holder.zip](https://github.com/p3d-dev/Print-To-3D/files/10880480/9.Draw.Holder.zip)

Gcode Preamble

M201 X1000 Y1000 Z200 E5000  ; accel
M203 X200 Y200 Z12 E120      ; feedrate
M204 P1250 R1250 T1250       ; accel
M205 X8.00 Y8.00 Z0.40 E4.50 ; jerk
M205 S0 T0                   ; min travel
M107                         ; disable cooling fan
M862.3 P "MK3S"              ; printer model check
M862.1 P0.4                  ; nozzle diameter check
M104 S160          ; set extruder temp
M140 S{bed_temp}   ; set bed temp
M190 S{bed_temp}   ; wait for bed temp
G28 W              ; home all without mesh bed level
G80                ; mesh bed leveling
G90                ; set absolute positioning mode
M83                ; set relative positioning for extruder
M900 K0.04         ; linear advance
G1 F1000           ; set feedrate
G1 Y-3.0 Z0.5      ; park outside print area
M104 S{temp}       ; set extruder actual required temp
M109 S{temp}       ; wait for extruder actual required temp
G1 X60.0 E9.0      ; purge line
G1 X100.0 E12.5    ; purge line
M117 Printing

Gcode Postamble 

G0 E-1 F900  ; retract slightly
M104 S0      ; turn off nozzle heat
M140 S0      ; turn off bed heat
M107         ; turn off fan
G0 F3000     ; set feedrate
G0 Y210 Z210 ; serve up print
G4           ; wait
M84          ; disable steppers
M117 Print Done

Gcode Layer

;; LAYER {layer} of {layers}
M117 Layer {layer} of {layers}

Gcode Progress

M73 P{progress}

Gcode Fan

M106 S{fan_speed}

![1B7F080B-1A00-4532-9D05-4C8C2A4E0C78](https://user-images.githubusercontent.com/79003022/222679832-1608fdd6-6d52-4c67-bbc6-45d432cd423c.jpeg)

Robin Harper

**Comment by p3d-dev** [comment] 2023-03-03 10:14
Hello Mr.Harper,

many thanks for sharing the detailed and very helpful bug report. Please accept our apology for this misbehavior.

The error can be reproduced on our side. A quick fix to make it work is by removing this line in the Gcode Preamble:
```
M862.3 P "MK3S" ; printer model check
```
Background: This line contains ", which in our internal string processing leads to this error. 
The next release of PrintTo3D will contain a fix for this, even though we need to identify the technical solution first.

**Comment by p3d-dev** [comment] 2023-03-03 11:11
V3.26 fixes this issue and has already been pushed to Apple for review.

**Comment by ghost** [comment] 2023-03-03 14:05
Great fixed. Had ago at slicing a few items and this was successfully achieved. 

However please find attached a couple of photos. Before and after slicing any idea why the slice is unsuccessful.
![5F5A81A2-A9BC-4355-A114-F2184B128658](https://user-images.githubusercontent.com/79003022/222739684-9c5aff87-eb75-4bf3-9ad9-0a8807628155.jpeg)
![1FA6D464-E991-43F6-8F75-B99E47D397B8](https://user-images.githubusercontent.com/79003022/222739731-5f5d848d-b206-4bca-ab16-34a59e5768d4.jpeg)
[9 Draw Holder.zip](https://github.com/p3d-dev/Print-To-3D/files/10882622/9.Draw.Holder.zip)
I have attached a 9 box version with the same issue.

**Comment by p3d-dev** [comment] 2023-03-03 16:04
Most likely, because this is not one part, but consists of 13 independent parts with tiny gaps or even overlapping parts. The slicing engine does not cope well with this.

Here is a view, with the surface shown in different colors:
![image](https://user-images.githubusercontent.com/105526632/222767903-7ad4e3ce-35b1-4042-854c-6d2dcd4796d3.png)

Long term plan is to provide a union function for such kind of parts. And possibility to separate the surfaces in individual parts.

**Comment by ghost** [comment] 2023-03-03 17:40
Many thanks for all your help.

Will look to redesign it from one block. 

One last question, I am only a hobbyist and I am looking to move to a tablet completely (laptop very old) and this appears a good fit. Are there any tutorials around the “Process Congratulation” looking to design something in line with Prusa slicer draft mode

**Comment by p3d-dev** [comment] 2023-04-01 09:37
Please open new discussions !

**Closed as completed** 2023-04-01 09:37 UTC
